config/routes.rb
Rails.application.routes.draw do
  resources :dblegos
  devise_for :utentis
  root 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dblego.rb
class Dblego < ApplicationRecord
end

app/models/utenti.rb
class Utenti < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:nome])
      devise_parameter_sanitizer.permit(:account_update, keys: [:nome])
    end
end

app/controllers/dblegos_controller.rb
class DblegosController < ApplicationController
  before_action :set_dblego, only: [:show, :edit, :update, :destroy]

  # GET /dblegos
  # GET /dblegos.json
  def index
    @dblegos = Dblego.all
  end

  # GET /dblegos/1
  # GET /dblegos/1.json
  def show
  end

  # GET /dblegos/new
  def new
    @dblego = Dblego.new
  end

  # GET /dblegos/1/edit
  def edit
  end

  # POST /dblegos
  # POST /dblegos.json
  def create
    @dblego = Dblego.new(dblego_params)

    respond_to do |format|
      if @dblego.save
        format.html { redirect_to @dblego, notice: 'Dblego was successfully created.' }
        format.json { render :show, status: :created, location: @dblego }
      else
        format.html { render :new }
        format.json { render json: @dblego.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dblegos/1
  # PATCH/PUT /dblegos/1.json
  def update
    respond_to do |format|
      if @dblego.update(dblego_params)
        format.html { redirect_to @dblego, notice: 'Dblego was successfully updated.' }
        format.json { render :show, status: :ok, location: @dblego }
      else
        format.html { render :edit }
        format.json { render json: @dblego.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dblegos/1
  # DELETE /dblegos/1.json
  def destroy
    @dblego.destroy
    respond_to do |format|
      format.html { redirect_to dblegos_url, notice: 'Dblego was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dblego
      @dblego = Dblego.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dblego_params
      params.require(:dblego).permit(:part, :color, :quantity)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dblegos_helper.rb
module DblegosHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/dblegos/_form.html.erb
<%= form_with(model: dblego, local: true) do |form| %>
  <% if dblego.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dblego.errors.count, "error") %> prohibited this dblego from being saved:</h2>

      <ul>
      <% dblego.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :part %>
    <%= form.text_field :part, id: :dblego_part %>
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.number_field :color, id: :dblego_color %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity, id: :dblego_quantity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/dblegos/edit.html.erb
<h1>Editing Dblego</h1>

<%= render 'form', dblego: @dblego %>

<%= link_to 'Show', @dblego %> |
<%= link_to 'Back', dblegos_path %>

app/views/dblegos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dblegos</h1>

<table>
  <thead>
    <tr>
      <th>Part</th>
      <th>Color</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dblegos.each do |dblego| %>
      <tr>
        <td><%= dblego.part %></td>
        <td><%= dblego.color %></td>
        <td><%= dblego.quantity %></td>
        <td><%= link_to 'Show', dblego %></td>
        <td><%= link_to 'Edit', edit_dblego_path(dblego) %></td>
        <td><%= link_to 'Destroy', dblego, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dblego', new_dblego_path %>

app/views/dblegos/new.html.erb
<h1>New Dblego</h1>

<%= render 'form', dblego: @dblego %>

<%= link_to 'Back', dblegos_path %>

app/views/dblegos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Part:</strong>
  <%= @dblego.part %>
</p>

<p>
  <strong>Color:</strong>
  <%= @dblego.color %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @dblego.quantity %>
</p>

<%= link_to 'Edit', edit_dblego_path(@dblego) %> |
<%= link_to 'Back', dblegos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BeRealBrick</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

  <main  class="container">
    <%= yield %>
  </main>

  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>